version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest $ECR_REPOSITORY:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $ECR_REPOSITORY:latest
      - echo Build completed successfully
